name: wt_name_that_color
description: "Library for managing the layout of an application.."
publish_to: 'none'
version: 0.1.7+8

environment:
  sdk: '>=3.2.5 <4.0.0'

scripts:
    get: flutter pub get
    clean: flutter pub get
    refresh: flutter clean; flutter pub get
    test: flutter test
    analyse: flutter analyze
    status: git status
    size:
      summary: du -sh *
      total: du -sh .
dependencies:
  collection: any

dev_dependencies:
  build_runner: any
  test: ^1.25.5
